import type { Metadata } from "next";
import ScrollSmootherProvider from "./components/Scroll-Smooth-Provider";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./footer/footer";
import "./globals.css";
import Header from "./header/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <div id="smooth-wrapper">
          <div id="smooth-content">
            <ScrollSmootherProvider />
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
